name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }} Build

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build and test
      run: mvn -B verify
      
    - name: Code coverage report
      uses: codecov/codecov-action@v3
      if: matrix.java == '17' # Only run coverage on one JDK version
      
    - name: SonarCloud analysis
      if: matrix.java == '17' && github.event_name == 'pull_request'
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build package
      run: mvn -B package -DskipTests
      
    - name: Deploy to GitHub Packages
      run: mvn deploy -DskipTests -DrepositoryId=repo-id -Durl=https://maven.pkg.github.com/hermann90/geolo #-Dusername=user -Dpassword=pass
      env:
        GITHUB_TOKEN: ${{ github.token }}